backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Accueil"
        name: "accueil"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Description", name: "body", widget: "markdown" }

      - file: "equipe.html"
        label: "Ã‰quipe"
        name: "equipe"
        fields:
          - { label: "Membre 1", name: "membre1", widget: "markdown" }
          - { label: "Membre 2", name: "membre2", widget: "markdown" }

      - file: "contact.html"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Informations de contact", name: "body", widget: "markdown" }