backend:
  name: github
  repo: "jordivuong/DangFantou"  # Remplacez par votre repo GitHub
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/index.md"
        label: "Accueil"
        name: "accueil"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Texte d'accueil", name: "body", widget: "markdown" }
          - { label: "Photo", name: "photo", widget: "image" }
          - { label: "Email contact", name: "email", widget: "string" }

      - file: "content/equipe.md"
        label: "Équipe"
        name: "equipe"
        fields:
          - { label: "Nom personne 1", name: "nom1", widget: "string" }
          - { label: "Présentation personne 1", name: "bio1", widget: "markdown" }
          - { label: "Photo personne 1", name: "photo1", widget: "image" }

          - { label: "Nom personne 2", name: "nom2", widget: "string" }
          - { label: "Présentation personne 2", name: "bio2", widget: "markdown" }
          - { label: "Photo personne 2", name: "photo2", widget: "image" }

      - file: "content/actualites.md"
        label: "Actualités"
        name: "actualites"
        fields:
          - { label: "Texte actualités", name: "body", widget: "markdown" }